index.js
package.json

- Settlenetにcfd-jsを利用してもらう際に、main fileがないことに気づいたため追加
- exportするモジュールは、wrap_js/cfdjs_module.js
- (Objectをインターフェースとして利用してもらう想定)
sandboxで
```bash
npm install
`wrap_js/example.js`などの"cfdjs_module"を"cfd-js"に変更
node wrap_js/example.js
```
- なし
**PRを出した人**
**レビューする人**

[hotfix]packageのmianファイルを追加

---

include/cfdjs/cfdjs_struct.h
include/cfdjs/cfdjs_utility.h
src/CMakeLists.txt
src/cfdapi_encode_signature_by_der_json.cpp
src/cfdapi_encode_signature_by_der_json.h
src/cfdjs_node_addon.cpp
src/cfdjs_utility.cpp
src/input_json_format/cfdapi_encode_signature_by_der.json
wrap_js/__test__/EncodeSignatureByDer.spec.js
wrap_js/example.js

- [#1046](https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1046)
- DEREncode を実施するAPIを作成
```bash
npm run check_all
```
- 
**PRを出した人**
**レビューする人**
- テストとして、非Compactな署名に対してDER Encodeのテストデータが見つからない
（できるライブラリが見つからなかった）ため、ライブラリが生成したもの定義しています。

DER Encode APIを作成

---

include/cfdjs/cfdjs_struct.h
include/cfdjs/cfdjs_utility.h
src/CMakeLists.txt
src/cfdapi_encode_signature_by_der_json.cpp
src/cfdapi_encode_signature_by_der_json.h
src/cfdjs_node_addon.cpp
src/cfdjs_utility.cpp
src/input_json_format/cfdapi_encode_signature_by_der.json
wrap_js/__test__/EncodeSignatureByDer.spec.js
wrap_js/example.js

- [#1046](https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1046)
- DEREncode を実施するAPIを作成
```bash
npm run check_all
```
- 
**PRを出した人**
**レビューする人**
- テストとして、非Compactな署名に対してDER Encodeのテストデータが見つからない
（できるライブラリが見つからなかった）ため、ライブラリが生成したもの定義しています。

add DerEncoding API

---

.gitattributes
.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml

- https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1039
- 1039: CI追加
```bash
```
- 
**PRを出した人**
**レビューする人**

add ci setting.

---

tools/cmake_cleanup.bat
tools/cmake_cleanup.sh

- https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1135
- cleanup scriptの追加
```bash
```
- 
**PRを出した人**
**レビューする人**

add cleanup script

---

include/cfdjs/cfdjs_struct.h
src/autogen/cfdapi_create_extkey_from_path_json.cpp
src/autogen/cfdapi_create_extkey_from_path_json.h
src/autogen/cfdapi_get_address_info_json.h
src/autogen/cfdapi_get_extkeyinfo_json.cpp
src/autogen/cfdapi_get_extkeyinfo_json.h
src/cfdjs_hdwallet.cpp
src/input_json_format/cfdapi_create_extkey_from_path.json
src/input_json_format/cfdapi_get_extkeyinfo.json
wrap_js/__test__/CreateExtkeyFromPath.spec.js
wrap_js/__test__/GetExtkeyInfo.spec.js

- https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1137
- 1137: cfd-jsへの機能追加
- 途中だがAPIのみ追加してタグを打つ。
- hdkeyのfingerprint情報
- path文字列からextkey算出
```bash
```
- 
**PRを出した人**
**レビューする人**

feature/descriptor 20200127-1

---

include/cfdjs/cfdjs_struct.h
index.d.ts
src/autogen/cfd_js_api_json_autogen.cpp
src/autogen/cfd_js_api_json_autogen.h
src/cfdjs_elements_address.cpp
src/input_json_format/cfdapi_elements_create_pegin_address.json
wrap_js/__test__/ElementsCreatePegInAddress.spec.js

- https://app.zenhub.com/workspaces/cfd-5cdbe88f0f84751dcd8fd7ab/issues/cryptogarageinc/btclib-sandbox/1148
- 1148: pegin address typeの指定。
- blind peginを行う場合、native segwitアドレスである必要がある。
```bash
```
- 
**PRを出した人**
**レビューする人**

add input pegin address format.

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml
.github/workflows/create_release-and-upload.yml
local_resource/external_project_local_setting.config

- update to sprint42
```bash
```
- 
**PRを出した人**
**レビューする人**

update to sprint42

---

cfdjs_util.d.ts
wrap_js/ts_example.ts

- add cfdjs_util.d.ts file.
```bash
```
- 
**PRを出した人**
**レビューする人**

fix: add cfdjs_util d.ts file

---

local_resource/external_project_local_setting.config

- hotfix: update to sprint44
```bash
```
- 
**PRを出した人**
**レビューする人**

update to sprint44(hotfix)

---

.github/workflows/create_release-and-upload.yml
wrap_js/cfdjs_module.js
wrap_js/cfdjs_raw_module.js

- update to v0.0.24
```bash
```
- 
**PRを出した人**
**レビューする人**

update to v0.0.24

---

local_resource/external_project_local_setting.config
package-lock.json
package.json
wrap_js/__test__/ElementsCreatePegInAddress.spec.js

- npm security update.
```bash
```
- 
**PRを出した人**
**レビューする人**

hotfix: security upgrade. (kind-of)

---

addon/cfdjs_node_addon.cpp
include/cfdjs/cfdjs_api_hdwallet.h
include/cfdjs/cfdjs_api_json.h
include/cfdjs/cfdjs_struct.h
index.d.ts
local_resource/external_project_local_setting.config
package-lock.json
package.json
src/autogen/cfd_js_api_json_autogen.cpp
src/autogen/cfd_js_api_json_autogen.h
src/cfdjs_hdwallet.cpp
src/cfdjs_json_mapping_api.cpp
src/input_json_format/cfdapi_create_extkey.json
tools/generate_json_map_class.js
wrap_js/__test__/CreateExtkey.spec.js
wrap_js/example.js

- feat: direct create extkey. update version.
```bash
```
- 
**PRを出した人**
**レビューする人**

feat: direct create extkey.

---

addon/cfdjs_node_addon.cpp
include/cfdjs/cfdjs_api_hdwallet.h
include/cfdjs/cfdjs_api_json.h
include/cfdjs/cfdjs_struct.h
index.d.ts
local_resource/external_project_local_setting.config
package-lock.json
package.json
src/autogen/cfd_js_api_json_autogen.cpp
src/autogen/cfd_js_api_json_autogen.h
src/cfdjs_hdwallet.cpp
src/cfdjs_json_mapping_api.cpp
src/input_json_format/cfdapi_create_extkey.json
tools/generate_json_map_class.js
wrap_js/__test__/CreateExtkey.spec.js
wrap_js/example.js

- update to v0.0.26
```bash
```
- 
**PRを出した人**
**レビューする人**

update to v0.0.26

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml
local_resource/external_project_local_setting.config
package-lock.json
package.json

- update to v0.0.28
- for dlc
```bash
```
- 
**PRを出した人**
**レビューする人**

update to v0.0.28

---

local_resource/external_project_local_setting.config

- 
```bash
```
- 
**PRを出した人**
**レビューする人**

upgrade: update cfd-core version.

---

.eslintignore
.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml
.github/workflows/create_release-and-upload.yml
package-lock.json
package.json
tools/generate_json_map_class.ts

- feat: add cross-env
```bash
```
- 
**PRを出した人**
**レビューする人**

feat: convert tool change js to ts.

---

include/cfdjs/cfdjs_api_elements_transaction.h
include/cfdjs/cfdjs_struct.h
index.d.ts
package-lock.json
package.json
src/autogen/cfd_js_api_json_autogen.cpp
src/autogen/cfd_js_api_json_autogen.h
src/cfdjs_elements_transaction.cpp
src/cfdjs_json_mapping_api.cpp
src/input_json_format/cfdapi_elements_create_destroy_amount.json
src/input_json_format/cfdapi_elements_create_raw_pegin.json
src/input_json_format/cfdapi_elements_create_raw_pegout.json

- re: update to v0.1.4
```bash
```
** Reviewer **

re: update to v0.1.4

---

package-lock.json
package.json

fix: version

---

.github/ISSUE_TEMPLATE/Story.md
.github/ISSUE_TEMPLATE/Task.md
addon/cfdjs_node_addon.cpp
include/cfdjs/cfdjs_api_json.h
include/cfdjs/cfdjs_api_utility.h
include/cfdjs/cfdjs_struct.h
index.d.ts
local_resource/external_project_local_setting.config
package-lock.json
package.json
src/autogen/cfd_js_api_json_autogen.cpp
src/autogen/cfd_js_api_json_autogen.h
src/cfdjs_json_mapping_api.cpp
src/cfdjs_utility.cpp
src/input_json_format/cfdapi_convert_aes.json
src/input_json_format/cfdapi_decode_base58.json
src/input_json_format/cfdapi_encode_base58.json
wrap_js/__test__/ConvertAes.spec.js
wrap_js/__test__/DecodeBase58.spec.js
wrap_js/__test__/EncodeBase58.spec.js
wrap_js/example.js

- update to v0.1.8
- doc: add issue template
- feat: add crypto API (aes, base58)
```bash
```
** Reviewer **

update to v0.1.8

---

local_resource/external_project_local_setting.config
package-lock.json
package.json
tools/generate_json_map_class.ts

- update to v0.2.0
- feat: libwally-core schnorr update
- doc: fix generate function return doc.
```bash
```
** Reviewer **

update to v0.2.0

---

.github/workflows/create_release-and-upload.yml
wrap_js/__test__/EstimateFee.spec.js

- refactor: collect upload url
```bash
```
** Reviewer **

refactor: collect upload url

---

index.d.ts
src/input_json_format/cfdapi_get_compressed_pubkey.json
src/input_json_format/cfdapi_get_privkey_wif.json
tools/generate_json_map_class.ts

- fix: lost GetCompressedPubkey & GetPrivkeyWif on index.d.ts
- bug on v0.2.4
```bash
```
** Reviewer **

fix: lost GetCompressedPubkey & GetPrivkeyWif on index.d.ts

---

addon/cfdjs_node_addon.cpp
include/cfdjs/cfdjs_api_json.h
include/cfdjs/cfdjs_api_key.h
include/cfdjs/cfdjs_struct.h
index.d.ts
local_resource/external_project_local_setting.config
src/CMakeLists.txt
src/autogen/cfd_js_api_json_autogen.cpp
src/autogen/cfd_js_api_json_autogen.h
src/cfdjs_json_mapping_api.cpp
src/cfdjs_schnorr.cpp
src/cfdjs_schnorr.h
src/input_json_format/cfdapi_get_schnorr_pubkey_from_privkey.json
src/input_json_format/cfdapi_schnorr_sign.json
src/input_json_format/cfdapi_schnorr_verify.json
wrap_js/__test__/GetSchnorrPubkeyFromPrivkey.spec.js
wrap_js/__test__/SchnorrSign.spec.js
wrap_js/__test__/SchnorrVerify.spec.js

NA
Add schnorr functions 
NA
NA
- [ X build successed
** Reviewer **

Add schnorr functions

---

.github/workflows/code_scanner.yml
pkg_getter.js

- feat: add code scanning
- fix: update tool (code scan check)
```bash
```
** Reviewer **

feat: add code scanning

---

local_resource/external_project_local_setting.config
package-lock.json
package.json

- update to v0.2.6
- update cfd v0.2.6
- test: add code scan
```bash
```
** Reviewer **

update to v0.2.6

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml

- test: build after npm install
- for node.js v15
```bash
```
** Reviewer **

test: build after npm install

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml
.github/workflows/create_release-and-upload.yml

- feat: using npm v7 on windows. and update setup-node version.
```bash
```
** Reviewer **

feat: using npm v7 on windows. and update setup-node version.

---

external/CMakeLists.txt

- feat: remove unused wally build
```bash
```
** Reviewer **

feat: remove unused wally build

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml
.github/workflows/create_release-and-upload.yml
addon/CMakeLists.txt
package-lock.json
package.json

- feat: change releases asset to N-API only.
```bash
```
** Reviewer **

feat: change releases asset to N-API only.

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml

- test: fix ubuntu version
```bash
```
** Reviewer **

test: fix ubuntu version

---

tools/generate_json_map_class.ts

- fix: update json converter (ts-morph, etc)
```bash
```
** Reviewer **

fix: update json converter (ts-morph, etc)

---

local_resource/external_project_local_setting.config

- fix: remove binding.gyp
- binding.gyp is not need the N-API.
```bash
```
** Reviewer **

fix: remove binding.gyp

---

local_resource/external_project_local_setting.config
package-lock.json
package.json
src/cfdjs_psbt.cpp
wrap_js/__test__/data/psbt_test.json

- fix: show psbt input bip32 data 
```bash
```
** Reviewer **

fix: show psbt input bip32 data 

---

local_resource/external_project_local_setting.config
package-lock.json
package.json
src/cfdjs_transaction.cpp
wrap_js/__test__/data/common_test.json
wrap_js/__test__/data/psbt_test.json

- feat: update cfd-core and update test
```bash
```
** Reviewer **

feat: update cfd-core and update test

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml
wrap_js/__integration_test__/elements.conf

- test: update CI
```bash
```
** Reviewer **

test: update CI

---

README.md
addon/cfdjs_node_addon.cpp
include/cfdjs/cfdjs_api_address.h
include/cfdjs/cfdjs_api_json.h
include/cfdjs/cfdjs_struct.h
index.d.ts
local_resource/external_project_local_setting.config
package-lock.json
package.json
src/autogen/cfd_js_api_json_autogen.cpp
src/autogen/cfd_js_api_json_autogen.h
src/cfdjs_address.cpp
src/cfdjs_json_mapping_api.cpp
src/input_json_format/taproot/cfdapi_analyze_tapscript_tree.json
src/input_json_format/taproot/cfdapi_get_tapbranch_info.json
wrap_js/__test__/TestAddress.spec.js
wrap_js/__test__/data/address_test.json
wrap_js/example/taproot.js

- feat: update v0.3.5
- feat: add taproot analyze API
- fix: rename roothash to basehash
- doc: update readme
```bash
```
** Reviewer **

feat: update v0.3.5

---

wrap_js/elements_example/decode_address.js

- test: add elements decode address example.
```bash
```
** Reviewer **

test: add elements decode address example.

---

.github/workflows/workflow_modify_checker.yml
wrap_js/__test__/data/key_test.json
wrap_js/elements_example/decode_address.js

- test: sighash rangeproof
- merge from master
```bash
```
** Reviewer **

test: sighash rangeproof

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml
addon/cfdjs_node_addon.cpp
include/cfdjs/cfdjs_api_elements_transaction.h
include/cfdjs/cfdjs_api_json.h
include/cfdjs/cfdjs_api_transaction.h
include/cfdjs/cfdjs_struct.h
index.d.ts
local_resource/external_project_local_setting.config
src/autogen/cfd_js_api_json_autogen.cpp
src/autogen/cfd_js_api_json_autogen.h
src/cfdjs_elements_transaction.cpp
src/cfdjs_json_mapping_api.cpp
src/cfdjs_transaction.cpp
src/input_json_format/tx/cfdapi_get_txin_index.json
src/input_json_format/tx/cfdapi_get_txout_index.json
src/input_json_format/tx/cfdapi_split_txout.json
wrap_js/__test__/TestConfidentialTransaction.spec.js
wrap_js/__test__/TestTransaction.spec.js
wrap_js/__test__/data/elements_address_test.json
wrap_js/__test__/data/elements_transaction_test.json
wrap_js/__test__/data/transaction_test.json

- feat: add SplitTxOut API
- feat: add GetTxInIndex & GetTxOutIndex  API
- test: update ci image. (bitcoin 0.21.1) 
```bash
```
** Reviewer **

feat: add SplitTxOut API

---

wrap_js/__integration_test__/elements_wallettest.spec.ts
wrap_js/__integration_test__/wallettest.spec.js

- test: fix jest v27
```bash
```
** Reviewer **

test: fix jest v27

---

.github/workflows/code_scanner.yml
package-lock.json
package.json

- feat: update ci & package
```bash
```
** Reviewer **

feat: update ci & package

---

.github/workflows/create_release-and-upload.yml
package-lock.json
package.json
src/CMakeLists.txt

- feat: update cmake on CI
- ref: https://gitlab.kitware.com/cmake/cmake/-/issues/23365
- ref: https://gitlab.kitware.com/cmake/cmake/-/issues/20565
- refactor: cmake on src dir
```bash
```
** Reviewer **

feat: update cmake on CI

---

.github/workflows/check_pre-merge_sprint.yml
.github/workflows/create_release-and-upload.yml
.github/workflows/docker/alpine_build_entrypoint.sh
.github/workflows/docker/alpine_release_entrypoint.sh
README.md
docker-compose.yml
package-lock.json
package.json
pkg_getter.js
tools/init_package.sh

#262
- feat: add alpine binary
- add CI & pkg_getter
- doc: add LD_LIBRARY_PATH on Alpine Linux
- test: update test image
- test: add node.js v18, remove node.js v17
```bash
```
** Reviewer **

feat: add alpine binary

---

tools/test_entrypoint.sh

- fix: add test script
- #263 
```bash
```
** Reviewer **

fix: add test script

---

package-lock.json
package.json

- feat: update package
- cmake-js, prebuild, etc...
```bash
```
** Reviewer **

feat: update package

---

.github/workflows/create_release-and-upload.yml
package-lock.json
package.json

- feat: update release asset to macos 11
- remove macos 10.15
- feat: update packages
```bash
```
** Reviewer **

feat: update release asset macos

---

package-lock.json
package.json
pkg_getter.js

- feat: update got version
- fix: xcode binary version to 11.7
```bash
```
** Reviewer **

feat: update got version, fix xcode binary version

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml
.github/workflows/create_release-and-upload.yml
.github/workflows/docker/test_bitcoin_entrypoint.sh
.github/workflows/docker/test_entrypoint.sh
docker-compose.yml
local_resource/external_project_local_setting.config
package-lock.json
package.json
tools/init_package.sh
tools/update_package.sh
wrap_js/__integration_test__/bitcoin-docker-entrypoint.sh
wrap_js/__integration_test__/docker-entrypoint.sh

- fix: arm64v8 build
- feat: update cfd library
- fix: libwally-core arm64/v8 build
- feat: update docker image
- for arm64/v8
- update package
```bash
```
** Reviewer **

fix: arm64v8 build

---

addon/CMakeLists.txt
addon/cfdjs_node_addon.cpp
include/cfdjs/cfdjs_api_json.h
include/cfdjs/cfdjs_api_key.h
include/cfdjs/cfdjs_struct.h
index.d.ts
package-lock.json
package.json
src/autogen/cfd_js_api_json_autogen.cpp
src/autogen/cfd_js_api_json_autogen.h
src/cfdjs_internal.h
src/cfdjs_json_mapping_api.cpp
src/cfdjs_key.cpp
src/cfdjs_schnorr.cpp
src/cfdjs_schnorr.h
src/cfdjs_utility.cpp
src/input_json_format/key/cfdapi_verify_ec_signature.json
src/input_json_format/schnorr/cfdapi_schnorr_verify.json
wrap_js/__test__/TestPubkey.spec.js
wrap_js/__test__/data/key_test.json

- feat: change cmake-js package
- feat: upgrade package
- feat: add VerifySignatureWithPubkey
- refactor: rename schnorr struct
```bash
```
** Reviewer **

feat: add VerifySignatureWithPubkey, update packages

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml
.github/workflows/create_release-and-upload.yml

- test: update support node version
- support node.js 20
- remove node.js 14
- update release node.js version (v18)
```bash
```
** Reviewer **

test: update support node version

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml

- fix: update set-output to GITHUB_OUTPUT
```bash
```
** Reviewer **

fix: update set-output to GITHUB_OUTPUT

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml

- test: add node.js 21, remove 19
```bash
```
** Reviewer **

test: add node.js 21, remove 19

---

.github/workflows/check_pre-merge_develop.yml
.github/workflows/check_pre-merge_master.yml
.github/workflows/check_pre-merge_sprint.yml
.github/workflows/code_scanner.yml
.github/workflows/create_release-and-upload.yml
pkg_getter.js

feat: update CI
